version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: posix4e-rsyslog-raftman_server_1
      APP_PORT: 8282

  server:
    image: pierredavidbelanger/raftman:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "514:514/udp"
      - "5514:5514/tcp"
    volumes:
      - ${APP_DATA_DIR}/data:/data
